# Generated by Django 5.2 on 2025-06-08 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FishingInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worm_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('t1_bait_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('t3_bait_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('t5_bait_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
