# Generated by Django 5.2 on 2025-06-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishingbait', '0002_alter_fishinginput_t1_bait_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishinginput',
            name='t1_bait_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fishinginput',
            name='t3_bait_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fishinginput',
            name='t5_bait_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
