# Generated by Django 5.2 on 2025-06-08 07:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishingbait', '0003_alter_fishinginput_t1_bait_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FishingInput',
            new_name='FishingBaitData',
        ),
    ]
