# Generated by Django 5.2 on 2025-06-08 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishingbait', '0004_rename_fishinginput_fishingbaitdata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='fishingbaitdata',
            old_name='t1_bait_price',
            new_name='t1_price',
        ),
        migrations.RenameField(
            model_name='fishingbaitdata',
            old_name='t5_bait_price',
            new_name='t3_price',
        ),
        migrations.RenameField(
            model_name='fishingbaitdata',
            old_name='t3_bait_price',
            new_name='t5_price',
        ),
        migrations.AlterField(
            model_name='fishingbaitdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
