# Generated by Django 5.2 on 2026-01-04 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('HERB', 'Herb'), ('ANIMAL_PRODUCT', 'Animal Product'), ('SCHNAPPS', 'Schnapps'), ('OTHER', 'Other')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PotionVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('tier', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('enchant', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserIngredientPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='potions.ingredient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_prices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'ingredient'], name='potions_use_user_id_017f63_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'ingredient'), name='uniq_user_ingredient')],
            },
        ),
        migrations.CreateModel(
            name='UserPotionPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('potion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='potions.potionvariant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='potion_prices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'potion'], name='potions_use_user_id_de15d5_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'potion'), name='uniq_user_potion')],
            },
        ),
    ]
