# Generated by Django 5.2 on 2025-06-15 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='potioninput',
            options={'verbose_name': 'Potion Market Data', 'verbose_name_plural': 'Potion Market Data'},
        ),
        migrations.RemoveField(
            model_name='potioninput',
            name='created_at',
        ),
        migrations.AddField(
            model_name='potioninput',
            name='T8_INVISIBILITY_0',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T8 Invisibility +0', null=True),
        ),
        migrations.AddField(
            model_name='potioninput',
            name='T8_INVISIBILITY_1',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T8 Invisibility +1', null=True),
        ),
        migrations.AddField(
            model_name='potioninput',
            name='T8_INVISIBILITY_2',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T8 Invisibility +2', null=True),
        ),
        migrations.AddField(
            model_name='potioninput',
            name='T8_INVISIBILITY_3',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T8 Invisibility +3', null=True),
        ),
        migrations.AddField(
            model_name='potioninput',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T2_ENERGY_0',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T2 Energy +0', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T2_ENERGY_1',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T2 Energy +1', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T2_ENERGY_2',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T2 Energy +2', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T2_ENERGY_3',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T2 Energy +3', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T2_HEALING_0',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T2 Healing +0', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T2_HEALING_1',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T2 Healing +1', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T2_HEALING_2',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T2 Healing +2', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T2_HEALING_3',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T2 Healing +3', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T3_ACID_0',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T3 Acid +0', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T3_ACID_1',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T3 Acid +1', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T3_ACID_2',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T3 Acid +2', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T3_ACID_3',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T3 Acid +3', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T3_CALMING_0',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T3 Calming +0', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T3_CALMING_1',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T3 Calming +1', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T3_CALMING_2',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T3 Calming +2', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T3_CALMING_3',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T3 Calming +3', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T3_CLEANSING_0',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T3 Cleansing +0', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T3_CLEANSING_1',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T3 Cleansing +1', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T3_CLEANSING_2',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T3 Cleansing +2', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T3_CLEANSING_3',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T3 Cleansing +3', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T3_GIGANTIFY_0',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T3 Gigantify +0', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T3_GIGANTIFY_1',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T3 Gigantify +1', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T3_GIGANTIFY_2',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T3 Gigantify +2', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T3_GIGANTIFY_3',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T3 Gigantify +3', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T3_RESISTANCE_0',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T3 Resistance +0', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T3_RESISTANCE_1',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T3 Resistance +1', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T3_RESISTANCE_2',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T3 Resistance +2', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T3_RESISTANCE_3',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T3 Resistance +3', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T3_STICKY_0',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T3 Sticky +0', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T3_STICKY_1',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T3 Sticky +1', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T3_STICKY_2',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T3 Sticky +2', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T3_STICKY_3',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T3 Sticky +3', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T4_BERSERK_0',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T4 Berserk +0', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T4_BERSERK_1',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T4 Berserk +1', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T4_BERSERK_2',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T4 Berserk +2', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T4_BERSERK_3',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T4 Berserk +3', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T4_ENERGY_0',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T4 Energy +0', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T4_ENERGY_1',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T4 Energy +1', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T4_ENERGY_2',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T4 Energy +2', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T4_ENERGY_3',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T4 Energy +3', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T4_GATHERING_0',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T4 Gathering +0', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T4_GATHERING_1',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T4 Gathering +1', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T4_GATHERING_2',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T4 Gathering +2', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T4_GATHERING_3',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T4 Gathering +3', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T4_HEALING_0',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T4 Healing +0', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T4_HEALING_1',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T4 Healing +1', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T4_HEALING_2',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T4 Healing +2', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T4_HEALING_3',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T4 Healing +3', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T4_HELLFIRE_0',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T4 Hellfire +0', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T4_HELLFIRE_1',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T4 Hellfire +1', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T4_HELLFIRE_2',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T4 Hellfire +2', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T4_HELLFIRE_3',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T4 Hellfire +3', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T4_POISON_0',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T4 Poison +0', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T4_POISON_1',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T4 Poison +1', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T4_POISON_2',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T4 Poison +2', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T4_POISON_3',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T4 Poison +3', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T4_TORNADO_0',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T4 Tornado +0', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T4_TORNADO_1',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T4 Tornado +1', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T4_TORNADO_2',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T4 Tornado +2', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T4_TORNADO_3',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T4 Tornado +3', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T5_ACID_0',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T5 Acid +0', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T5_ACID_1',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T5 Acid +1', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T5_ACID_2',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T5 Acid +2', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T5_ACID_3',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T5 Acid +3', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T5_CALMING_0',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T5 Calming +0', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T5_CALMING_1',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T5 Calming +1', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T5_CALMING_2',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T5 Calming +2', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T5_CALMING_3',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T5 Calming +3', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T5_CLEANSING_0',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T5 Cleansing +0', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T5_CLEANSING_1',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T5 Cleansing +1', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T5_CLEANSING_2',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T5 Cleansing +2', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T5_CLEANSING_3',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T5 Cleansing +3', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T5_GIGANTIFY_0',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T5 Gigantify +0', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T5_GIGANTIFY_1',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T5 Gigantify +1', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T5_GIGANTIFY_2',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T5 Gigantify +2', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T5_GIGANTIFY_3',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T5 Gigantify +3', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T5_RESISTANCE_0',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T5 Resistance +0', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T5_RESISTANCE_1',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T5 Resistance +1', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T5_RESISTANCE_2',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T5 Resistance +2', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T5_RESISTANCE_3',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T5 Resistance +3', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T5_STICKY_0',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T5 Sticky +0', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T5_STICKY_1',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T5 Sticky +1', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T5_STICKY_2',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T5 Sticky +2', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T5_STICKY_3',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T5 Sticky +3', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T6_BERSERK_0',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T6 Berserk +0', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T6_BERSERK_1',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T6 Berserk +1', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T6_BERSERK_2',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T6 Berserk +2', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T6_BERSERK_3',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T6 Berserk +3', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T6_ENERGY_0',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T6 Energy +0', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T6_ENERGY_1',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T6 Energy +1', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T6_ENERGY_2',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T6 Energy +2', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T6_ENERGY_3',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T6 Energy +3', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T6_GATHERING_0',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T6 Gathering +0', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T6_GATHERING_1',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T6 Gathering +1', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T6_GATHERING_2',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T6 Gathering +2', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T6_GATHERING_3',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T6 Gathering +3', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T6_HEALING_0',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T6 Healing +0', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T6_HEALING_1',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T6 Healing +1', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T6_HEALING_2',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T6 Healing +2', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T6_HEALING_3',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T6 Healing +3', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T6_HELLFIRE_0',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T6 Hellfire +0', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T6_HELLFIRE_1',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T6 Hellfire +1', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T6_HELLFIRE_2',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T6 Hellfire +2', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T6_HELLFIRE_3',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T6 Hellfire +3', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T6_POISON_0',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T6 Poison +0', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T6_POISON_1',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T6 Poison +1', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T6_POISON_2',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T6 Poison +2', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T6_POISON_3',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T6 Poison +3', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T6_TORNADO_0',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T6 Tornado +0', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T6_TORNADO_1',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T6 Tornado +1', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T6_TORNADO_2',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T6 Tornado +2', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T6_TORNADO_3',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T6 Tornado +3', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T7_ACID_0',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T7 Acid +0', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T7_ACID_1',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T7 Acid +1', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T7_ACID_2',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T7 Acid +2', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T7_ACID_3',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T7 Acid +3', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T7_CALMING_0',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T7 Calming +0', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T7_CALMING_1',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T7 Calming +1', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T7_CALMING_2',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T7 Calming +2', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T7_CALMING_3',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T7 Calming +3', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T7_CLEANSING_0',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T7 Cleansing +0', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T7_CLEANSING_1',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T7 Cleansing +1', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T7_CLEANSING_2',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T7 Cleansing +2', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T7_CLEANSING_3',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T7 Cleansing +3', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T7_GIGANTIFY_0',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T7 Gigantify +0', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T7_GIGANTIFY_1',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T7 Gigantify +1', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T7_GIGANTIFY_2',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T7 Gigantify +2', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T7_GIGANTIFY_3',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T7 Gigantify +3', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T7_RESISTANCE_0',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T7 Resistance +0', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T7_RESISTANCE_1',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T7 Resistance +1', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T7_RESISTANCE_2',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T7 Resistance +2', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T7_RESISTANCE_3',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T7 Resistance +3', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T7_STICKY_0',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T7 Sticky +0', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T7_STICKY_1',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T7 Sticky +1', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T7_STICKY_2',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T7 Sticky +2', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T7_STICKY_3',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T7 Sticky +3', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T8_BERSERK_0',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T8 Berserk +0', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T8_BERSERK_1',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T8 Berserk +1', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T8_BERSERK_2',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T8 Berserk +2', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T8_BERSERK_3',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T8 Berserk +3', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T8_GATHERING_0',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T8 Gathering +0', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T8_GATHERING_1',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T8 Gathering +1', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T8_GATHERING_2',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T8 Gathering +2', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T8_GATHERING_3',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T8 Gathering +3', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T8_HELLFIRE_0',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T8 Hellfire +0', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T8_HELLFIRE_1',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T8 Hellfire +1', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T8_HELLFIRE_2',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T8 Hellfire +2', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T8_HELLFIRE_3',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T8 Hellfire +3', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T8_POISON_0',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T8 Poison +0', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T8_POISON_1',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T8 Poison +1', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T8_POISON_2',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T8 Poison +2', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T8_POISON_3',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T8 Poison +3', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T8_TORNADO_0',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T8 Tornado +0', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T8_TORNADO_1',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T8 Tornado +1', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T8_TORNADO_2',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T8 Tornado +2', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='T8_TORNADO_3',
            field=models.PositiveIntegerField(blank=True, help_text='Sale price for T8 Tornado +3', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='agaric',
            field=models.PositiveIntegerField(blank=True, help_text='Arcane Agaric (T2)', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='animal_remains',
            field=models.PositiveIntegerField(blank=True, help_text='Used for enchanting potions (+1, +2, +3)', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='burdock',
            field=models.PositiveIntegerField(blank=True, help_text='Crenellated Burdock (T4)', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='comfrey',
            field=models.PositiveIntegerField(blank=True, help_text='Brightleaf Comfrey (T3)', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='foxglove',
            field=models.PositiveIntegerField(blank=True, help_text='Elusive Foxglove (T6)', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='mullein',
            field=models.PositiveIntegerField(blank=True, help_text='Firetouched Mullein (T7)', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='teasel',
            field=models.PositiveIntegerField(blank=True, help_text='Dragon Teasel (T5)', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='potion_input', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='yarrow',
            field=models.PositiveIntegerField(blank=True, help_text='Ghoul Yarrow (T8)', null=True),
        ),
    ]
