# Generated by Django 5.2 on 2025-06-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potions', '0002_alter_potioninput_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potioninput',
            name='agaric',
            field=models.PositiveIntegerField(blank=True, help_text='Arcane Agaric', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='burdock',
            field=models.PositiveIntegerField(blank=True, help_text='Crenellated Burdock', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='comfrey',
            field=models.PositiveIntegerField(blank=True, help_text='Brightleaf Comfrey', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='foxglove',
            field=models.PositiveIntegerField(blank=True, help_text='Elusive Foxglove', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='mullein',
            field=models.PositiveIntegerField(blank=True, help_text='Firetouched Mullein', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='teasel',
            field=models.PositiveIntegerField(blank=True, help_text='Dragon Teasel', null=True),
        ),
        migrations.AlterField(
            model_name='potioninput',
            name='yarrow',
            field=models.PositiveIntegerField(blank=True, help_text='Ghoul Yarrow', null=True),
        ),
    ]
