# Generated by Django 5.2 on 2026-01-04 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtifactItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code_base', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArtifactPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('RUGGED', 'Rugged (T3)'), ('FINE', 'Fine (T5)'), ('EXCELLENT', 'Excellent (T7)')], max_length=10)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='animal_artifacts.artifactitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifact_prices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'item'], name='animal_arti_user_id_5f2925_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'item', 'tier'), name='uniq_user_item_tier')],
            },
        ),
    ]
