# Generated by Django 5.2 on 2025-06-06 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.CharField(choices=[('Rugged', 'Rugged'), ('Fine', 'Fine'), ('Excellent', 'Excellent')], default='Rugged', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_artifacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnimalArtifactItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Shadow Claws', 'Shadow Claws'), ('Sylvian Roots', 'Sylvian Roots'), ('Spirit Paws', 'Spirit Paws'), ('Werewolf Fangs', 'Werewolf Fangs'), ("Imp's Horn", "Imp's Horn"), ('Runestone Tooth', 'Runestone Tooth'), ('Dawnfeather', 'Dawnfeather')], max_length=50)),
                ('market_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('code_name', models.CharField(max_length=100)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='animal_artifacts.animalartifact')),
            ],
        ),
    ]
