# Generated by Django 5.2 on 2025-05-29 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('Rugged', 'Rugged'), ('Fine', 'Fine'), ('Excellent', 'Excellent')], max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnimalArtifactItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('market_price', models.PositiveIntegerField(blank=True, null=True)),
                ('code_name', models.CharField(default='entercodenamebro', max_length=100)),
                ('artifact_tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='animal_artifacts.animalartifact')),
            ],
        ),
    ]
