# Generated by Django 5.2 on 2025-05-29 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_artifacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalartifactitem',
            name='code_name',
            field=models.CharField(max_length=100),
        ),
    ]
