# Generated by Django 5.2 on 2025-06-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_artifacts', '0002_alter_animalartifactitem_market_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalartifact',
            name='artifact_type',
            field=models.CharField(choices=[('Rugged', 'Rugged'), ('Fine', 'Fine'), ('Excellent', 'Excellent')], max_length=10),
        ),
    ]
