# Generated by Django 5.2 on 2025-05-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_artifacts', '0002_alter_animalartifactitem_code_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalartifactitem',
            name='code_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
