# Generated by Django 5.2 on 2025-06-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_artifacts', '0003_alter_animalartifact_artifact_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalartifactitem',
            name='market_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='animalartifactitem',
            name='name',
            field=models.CharField(choices=[('Shadow Claws', 'Shadow Claws'), ('Sylvian Roots', 'Sylvian Roots'), ('Spirit Paws', 'Spirit Paws'), ('Werewolf Fangs', 'Werewolf Fangs'), ("Imp's Horn", "Imp's Horn"), ('Runestone Tooth', 'Runestone Tooth'), ('Dawnfeather', 'Dawnfeather')], max_length=100),
        ),
    ]
