# Generated by Django 5.2 on 2025-06-06 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_artifacts', '0004_alter_animalartifactitem_market_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalartifactitem',
            name='market_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
